import { GridSettings, Cell, Area, CellArray } from './gridset.d';
export declare const colCells: (ci: number, grid: GridSettings) => CellArray;
export declare const rowCells: (ri: number, grid: GridSettings) => CellArray;
export declare const cols: (grid: GridSettings) => Area;
export declare const rows: (grid: GridSettings) => Area;
export declare const flatCells: (grid: GridSettings) => (Cell | null)[];
export declare const diagonal: (grid: GridSettings) => (ci: number, ri: number) => CellArray;
export declare const antidiagonal: (grid: GridSettings) => (ci: number, ri: number) => (Cell | null)[];
export declare const area: (grid: GridSettings) => ({ ci1, ri1, ci2, ri2, }: {
    ci1: number;
    ri1: number;
    ci2: number;
    ri2: number;
}) => {
    x: number;
    y: number;
    w: number;
    h: number;
    t: number;
    l: number;
    r: number;
    b: number;
    cx: number;
    cy: number;
    cells: ({
        _u: (mode: string) => Cell | null | undefined;
        _lu: (mode: string) => Cell | null | undefined;
        _ru: (mode: string) => Cell | null | undefined;
        _d: (mode: string) => Cell | null | undefined;
        _ld: (mode: string) => Cell | null | undefined;
        _rd: (mode: string) => Cell | null | undefined;
        _r: (mode: string) => Cell | null | undefined;
        _l: (mode: string) => Cell | null | undefined;
        x: number;
        y: number;
        t: number;
        l: number;
        b: number;
        r: number;
        w: number;
        h: number;
        cx: number;
        cy: number;
        ci: number;
        ri: number;
    } | null)[][];
} | undefined;
export declare const areaByCell: (grid: GridSettings) => (cell1: Cell, cell2: Cell) => {
    x: number;
    y: number;
    w: number;
    h: number;
    t: number;
    l: number;
    r: number;
    b: number;
    cx: number;
    cy: number;
    cells: ({
        _u: (mode: string) => Cell | null | undefined;
        _lu: (mode: string) => Cell | null | undefined;
        _ru: (mode: string) => Cell | null | undefined;
        _d: (mode: string) => Cell | null | undefined;
        _ld: (mode: string) => Cell | null | undefined;
        _rd: (mode: string) => Cell | null | undefined;
        _r: (mode: string) => Cell | null | undefined;
        _l: (mode: string) => Cell | null | undefined;
        x: number;
        y: number;
        t: number;
        l: number;
        b: number;
        r: number;
        w: number;
        h: number;
        cx: number;
        cy: number;
        ci: number;
        ri: number;
    } | null)[][];
};
