import { GridSettings } from './gridset.d';
export declare const calcXy: (rici: number, wh: string, grid: GridSettings) => number;
export declare const cell: (ci: number, ri: number, grid: GridSettings) => {
    _u: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _lu: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _ru: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _d: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _ld: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _rd: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _r: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _l: (mode: string) => import("./gridset.d").Cell | null | undefined;
    x: number;
    y: number;
    t: number;
    l: number;
    b: number;
    r: number;
    w: number;
    h: number;
    cx: number;
    cy: number;
    ci: number;
    ri: number;
} | null;
export declare const looks: (ci: number, ri: number, grid: GridSettings) => {
    _u: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _lu: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _ru: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _d: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _ld: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _rd: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _r: (mode: string) => import("./gridset.d").Cell | null | undefined;
    _l: (mode: string) => import("./gridset.d").Cell | null | undefined;
};
